name: Run Python Program

on:
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run Python file
        run: - name: List Python files
  run: find . -type f -name "*.py" -print
name: List Python files
run: find . -type f -name "*.py" -print
name: Run Python filerun: python ./day7_gaming_guess.py
